title: mainguyent's Website
description: Personal website of mainguyent
baseurl: ""
url: "https://mainguyent.github.io"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
